Added Commonly asked questions
dankgrinder/dankgrinder pull request #25
Opened 2021-04-01 13:25 UTC by ihavezerohealth

Added "Commonly asked questions" section and added a couple of questions that I have seen in the Dank Grinder Discord.
If there are any errors, please tell me, thanks!
It'll help us all out so we don't have to nek snapp

2021-04-01 13:46 UTC, dankgrinder requested changes
Looks good. I have some minor reservations which I have addressed in my review. If you want to, adding the frequently asked questions which are currently only on Discord would also be appreciated!

2021-04-01 13:46 UTC, dankgrinder commented on README.md
> +### Commonly asked questions
```suggestion
## Commonly asked questions
```

2021-04-01 13:46 UTC, dankgrinder commented on README.md
> +## How do I disable certain features?
```suggestion
### How do I disable certain features?
```

2021-04-01 13:46 UTC, dankgrinder commented on README.md
> +## How do I disable global events?
```suggestion
### How do I disable global events?
```

2021-04-01 13:46 UTC, dankgrinder commented on README.md
> +## Can I run it on other architectures?
```suggestion
### Can I run it on other architectures?
```

2021-04-01 13:46 UTC, dankgrinder commented on README.md
> +You can remove a specific feature by removing it from the config, setting its "enable" value to false, or by setting the cooldown at the bottom of the config to a very high number.
```suggestion
You can remove a specific feature by removing it from the config, setting its `enable` value to `false`.
```

2021-04-04 14:17 UTC, dankgrinder commented
Still waiting for some requested changes. Do you want to approve those or cancel the PR?

2021-04-04 16:18 UTC, ihavezerohealth commented
how do I do that haha

On Sun, 4 Apr 2021, 15:18 dankgrinder, ***@***.***> wrote:

> Still waiting for some requested changes. Do you want to approve those or
> cancel the PR?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dankgrinder/dankgrinder/pull/25#issuecomment-813041130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS5JOFAXO76BLW3TU72DP53THBYJZANCNFSM42HC7CVQ>
> .
>

2021-04-17 19:24 UTC, Tripp-collins commented
i go banned on the bot i hate this

2021-05-07 03:38 UTC, Cherry-Picked-0001 commented
Why doesn't this work for bots? I mean shouldn't it be able to send messages if the bot's token is entered. I turned off all the Dank Memer commands and added custom commands but it doesn't work. Does this not work for bots?

2021-05-15 00:13 UTC, pythonmcpi commented
> Why doesn't this work for bots? I mean shouldn't it be able to send messages if the bot's token is entered. I turned off all the Dank Memer commands and added custom commands but it doesn't work. Does this not work for bots?

Dankgrinder was made to be used with a user token. The login process for user and bot tokens is slightly different, so you would have to modify the source code (and possibly a lot of it depending on how it is written) to get it working with a bot token. It would be easier to write your own bot in discord.py or discord.js (or other languages).

2021-05-17 02:08 UTC, dankgrinder commented
Closing due to inactivity

2021-05-17 02:08 UTC, closed without merging